// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfXdhMoYWjgcTkP5yk5AnDCplgWbtq8BQ',
    appId: '1:599895027153:web:567b597068c29fdbf204f0',
    messagingSenderId: '599895027153',
    projectId: 'lookslab-2b9b3',
    authDomain: 'lookslab-2b9b3.firebaseapp.com',
    storageBucket: 'lookslab-2b9b3.firebasestorage.app',
    measurementId: 'G-8Q0HN37MTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2vV56Eu_Hpz2SyeroM3Ap_1KpXLfZrtQ',
    appId: '1:599895027153:android:743a3d10d9302374f204f0',
    messagingSenderId: '599895027153',
    projectId: 'lookslab-2b9b3',
    storageBucket: 'lookslab-2b9b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1LPnv0NmQQT6TYbMHGVbZYoKDzyCpvm0',
    appId: '1:599895027153:ios:d89b1d495ee9b01af204f0',
    messagingSenderId: '599895027153',
    projectId: 'lookslab-2b9b3',
    storageBucket: 'lookslab-2b9b3.firebasestorage.app',
    iosBundleId: 'com.nexvoltsolutions.looklabs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1LPnv0NmQQT6TYbMHGVbZYoKDzyCpvm0',
    appId: '1:599895027153:ios:d89b1d495ee9b01af204f0',
    messagingSenderId: '599895027153',
    projectId: 'lookslab-2b9b3',
    storageBucket: 'lookslab-2b9b3.firebasestorage.app',
    iosBundleId: 'com.nexvoltsolutions.looklabs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfXdhMoYWjgcTkP5yk5AnDCplgWbtq8BQ',
    appId: '1:599895027153:web:79605b69c8776c94f204f0',
    messagingSenderId: '599895027153',
    projectId: 'lookslab-2b9b3',
    authDomain: 'lookslab-2b9b3.firebaseapp.com',
    storageBucket: 'lookslab-2b9b3.firebasestorage.app',
    measurementId: 'G-G4LKK9VZ86',
  );
}
